// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX87vqTKCNtLzNdkgerzjb82Nl8wwPGvA',
    appId: '1:509410210521:web:a2f37d1be53d7fafd684c8',
    messagingSenderId: '509410210521',
    projectId: 'flutter-firebase-c2ed5',
    authDomain: 'flutter-firebase-c2ed5.firebaseapp.com',
    storageBucket: 'flutter-firebase-c2ed5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJQX37BZ51PxftCq_UZg9Ajm4x-UGFVY',
    appId: '1:509410210521:android:04ae436ff09f3becd684c8',
    messagingSenderId: '509410210521',
    projectId: 'flutter-firebase-c2ed5',
    storageBucket: 'flutter-firebase-c2ed5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqTwriElTqp6BA39rU5lj1CbkMMgAenAY',
    appId: '1:509410210521:ios:57744949babda01bd684c8',
    messagingSenderId: '509410210521',
    projectId: 'flutter-firebase-c2ed5',
    storageBucket: 'flutter-firebase-c2ed5.appspot.com',
    androidClientId: '509410210521-ppmqhp68esi3b2s24l790j8f2lqjbhl1.apps.googleusercontent.com',
    iosClientId: '509410210521-ipcftt5n2vsth9s3gg7dhgl2iob8t6pd.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqTwriElTqp6BA39rU5lj1CbkMMgAenAY',
    appId: '1:509410210521:ios:63ab79c179db70d7d684c8',
    messagingSenderId: '509410210521',
    projectId: 'flutter-firebase-c2ed5',
    storageBucket: 'flutter-firebase-c2ed5.appspot.com',
    androidClientId: '509410210521-ppmqhp68esi3b2s24l790j8f2lqjbhl1.apps.googleusercontent.com',
    iosClientId: '509410210521-jgl4k86jaa0na5ojf0d2kfb8he333uls.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebaseFlutter.RunnerTests',
  );
}
